name: CI

on:
  push:
    branches-ignore:
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              env:
                  packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                  packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                  ./gradlew build
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@2201.0.0
              with:
                  args: pack ./twitter
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action@2201.0.0
              with:
                  args: test ./twitter
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  API_KEY: ${{ secrets.API_KEY }}
                  API_SECRET: ${{ secrets.API_SECRET }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
                  DEV_ENVIRONMENT_NAME: ${{ secrets.DEV_ENVIRONMENT_NAME }}
                  CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
                  PORT: ${{ secrets.PORT }}
                  
